name: "Python wheels: build & release"

on:
  push:
    tags:
    - 'v*'

jobs:
  linux_wheels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: messense/maturin-action@v1
      with:
        manylinux: auto
        command: build
        args: --release -o dist --manifest-path crates/stringmetrics_py/Cargo.toml
    # NOTE: Seems to only build musl wheels for cpython 3.8
    - uses: messense/maturin-action@v1
      with:
        maturin-version: "v0.13.0"
        target: x86_64-unknown-linux-musl
        manylinux: musllinux_1_1
        command: build
        args: --release -o dist --find-interpreter --manifest-path crates/stringmetrics_py/Cargo.toml
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  windows_wheels:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --no-sdist -o dist --manifest-path crates/stringmetrics_py/Cargo.toml
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  macos_wheels:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: messense/maturin-action@v1
      with:
        command: build
        args: --release --no-sdist -o dist --universal2 --manifest-path crates/stringmetrics_py/Cargo.toml
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist

  release_all_wheels:
    name: Release
    runs-on: ubuntu-latest
    # needs: [ linux ]
    needs: [ linux_wheels, macos_wheels, windows_wheels ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Publish to PyPI
        uses: messense/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --skip-existing *
